---
scap_content: /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml

# scap profiles
scap_profile_anssi_bp28_enhanced: xccdf_org.ssgproject.content_profile_anssi_bp28_enhanced	
scap_profile_anssi_bp28_high: xccdf_org.ssgproject.content_profile_anssi_bp28_high	
scap_profile_anssi_bp28_intermediary: xccdf_org.ssgproject.content_profile_anssi_bp28_intermediary	
scap_profile_anssi_bp28_minimal: xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
scap_profile_cis_server_l2: xccdf_org.ssgproject.content_profile_cis
scap_profile_cis_server_l1: xccdf_org.ssgproject.content_profile_cis_server_l1
scap_profile_cis_workstation_l1: xccdf_org.ssgproject.content_profile_cis_workstation_l1		
scap_profile_cis_workstation_l2: xccdf_org.ssgproject.content_profile_cis_workstation_l2
scap_profile_cui: xccdf_org.ssgproject.content_profile_cui
scap_profile_e8: xccdf_org.ssgproject.content_profile_e8
scap_profile_hipaa: xccdf_org.ssgproject.content_profile_hipaa
scap_profile_ism_o: xccdf_org.ssgproject.content_profile_ism_o
scap_profile_ospp: xccdf_org.ssgproject.content_profile_ospp
scap_profile_pci_dss: xccdf_org.ssgproject.content_profile_pci-dss
scap_profile_stig: xccdf_org.ssgproject.content_profile_stig
scap_profile_stig_gui: xccdf_org.ssgproject.content_profile_stig_gui
